---
title: "README"
output: github_document
---

**7a.**

The main idea of this party of the script is to help getting the Spectral Centroids and Trajectory Length. By using this portion of the script we are trying to get the five equidistant locations(20%, 35%, 50%, 65%, 80%) of the vowel(durationV).

**7b.**

The script loads the WAV file we recorded, and using a loop to get item and vowel labels using the textgrid we created. Then, still in the loop, according to the interval tiers we created, the scripts gets formants at the time landmarks of 20% 35% 50% 65% and 80% of each vowel, also it calculates the spectral centroids and trajectory length using the formants. Finally it saves results to a CSV file.

**7c.**

In pa_2 we cut the one long recording to different short sound files containing only one word, and in each short sound file we do the segmentation and extract the data. In pa_3 we don't cut the one long recording, and just use the interval tiers of the textgrid to "tell" the loop what to do. The advantage of pa_3 way of doing it is that we don't generate unwanted files, and it saves time. However, the short sound files of single words may come handy for more analysis.


```{r}
library(tidyverse)
library(tidyr)
library(dplyr)
library(here)

vowel_data <- read_csv('./data/vowel_data.csv')

#calculate average F1/F2 centroids and trajectory length (include SD)
sum_vowel_data<-vowel_data %>% 
  group_by(vowel, language) %>% 
  summarize(f1_cent_avg = mean(f1_cent), sd_f1 = sd(f1_cent), f2_cent_avg = mean(f2_cent),sd_f2 = sd(f2_cent), tl_avg = mean(tl), sd_tl = sd(tl))

#trajectory length as a function of vowel and language
vowel_data %>% 
  ggplot(., aes(x = vowel, y = tl, color = language)) + 
    geom_boxplot(alpha = 0.7)

#F1 as a function of vowel and language
#solution 1
#vowel_data %>% 
#  ggplot(., aes(x = language, y = f1_cent, color = vowel)) + 
#    geom_boxplot(alpha = 0.7)
#solution 1.5
vowel_data %>% 
  ggplot(., aes(x = vowel, y = f1_cent, color = language)) + 
    geom_boxplot(alpha = 0.7)
#solution 2
#vowel_data %>% 
#  unite(., col = vowel_language, vowel, language, sep = "_", remove = FALSE) %>% 
#  ggplot(., aes(x = vowel_language, y = f1_cent)) + 
#    geom_boxplot(alpha = 1)
#solution 3
#vowel_data %>%
#  ggplot(aes(x = vowel, y = f1_cent)) +
#  geom_boxplot() +
#  facet_wrap(vars(language), ncol = 2) +
#  labs(x = "vowels", y = "f1 centroid value")

#F2 as a function of vowel and language
vowel_data %>% 
  ggplot(., aes(x = vowel, y = f2_cent, color = language)) + 
    geom_boxplot(alpha = 0.7)
#I'll just keep them 

#Preparing DF for Bonus
tl_vowel_data<-vowel_data %>% 
  group_by(vowel, language) %>% 
  summarize(f1_20 = mean(f1_20), f1_35 = mean(f1_35), f1_50 = mean(f1_50), f1_65 = mean(f1_65), f1_80 = mean(f1_80), f2_20 = mean(f2_20), f2_35 = mean(f2_35), f2_50 = mean(f2_50), f2_65 = mean(f2_65), f2_80 = mean(f2_80))
#longer
vowel_data_long<-tl_vowel_data %>% 
  pivot_longer(., cols=f1_20:f2_80, names_pattern = "(.*)_(.*)", names_to = c("formant", "time")) %>% 
  pivot_wider(., names_from = formant, values_from = value)

#(Bonus) Plot trajectory length in F1/F2 vowel space (don't know how to draw the fancy point-line thingy )

vowel_data_long %>% 
  ggplot(., aes(x = f2, y = f1, color = vowel, shape = language)) +
    geom_point(alpha = 0.5, size = 4) + 
    geom_path(alpha = 0.6) +
    geom_label(data = sum_vowel_data, aes(x = f2_cent_avg, y = f1_cent_avg, label = vowel, color = vowel), size = 5, alpha = 0.3) +
    scale_y_reverse() + 
    scale_x_reverse()


#(Bonus) Plot spectral centroids in F1/F2 vowel space
vowel_data %>% 
  ggplot(., aes(x = f2_cent, y = f1_cent, color = vowel, shape = language)) +
    geom_point(alpha = 0.5, size = 4) + 
    geom_text(data = sum_vowel_data, aes(x = f2_cent_avg, y = f1_cent_avg, label = vowel, color = vowel), size = 5) +
    scale_y_reverse() + 
    scale_x_reverse()

```
